###
GET http://localhost:5000/user
Content-Type: application/json
###

###
GET http://localhost:5000/user/683761410b612cec29442a66
Content-Type: application/json
###


###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Caio",
    "email": "Caio@gmail.com",
    "password": "1234567"    
}
###

###
PATCH  http://localhost:5000/users/6839c42950af5b354a975e06
Content-Type: application/json

{
    "name": "Felca",
    "email": "Felca@gmail.com",
    "password": "1234567"    
}
###